name: 'Pull Request closer'
description: 'Closes pull requests'
inputs:
    github-token:
        description: 'The github token'
        required: true
    authors-overriding-closing:
        description: 'Comma separated string of authors (github usernames) that can override the closing of a pull request.'
        required: false
        default: ''
    base-authors-overriding-closing:
        description: 'Same as authors-overriding-closing but will be added additionally. Set empty to remove our basic authors.'
        required: false
        default: 'pmSven,pmMarcel,pmAram'
    override-closing-comment:
        description: 'The comment that is needed to override the closing of a pull request.'
        required: false
        default: 'LintingIsFine'
    closing-comment:
        description: 'The comment that will be added to the pull request when it is closed.'
        required: false
        default: "We do not accept PRs with Linting errors. If you have any questions, please feel free to contact your project lead developer."
runs:
  using: 'node16'
  main: 'dist/index.js'
